# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=5

MODULE_AUTHOR="ROBN"
MODULE_VERSION="0.002"


inherit perl-module

DESCRIPTION="A tiny Prometheus client"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND="dev-perl/HTTP-Message
	dev-perl/Plack
	dev-lang/perl"
