# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="ROBN"
DIST_VERSION="0.07"


inherit perl-module

DESCRIPTION="A safer HTTP::Tiny"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND="dev-perl/Class-Method-Modifiers
	perl-gcpan/Net-DNS-Paranoid
	dev-lang/perl"
