# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="TIMLEGGE"
DIST_VERSION="0.35"

inherit perl-module

DESCRIPTION="OpenSSL Verify certificate verification in XS."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND=">=dev-perl/File-Slurper-0.14.0
	perl-gcpan/Crypt-OpenSSL-X509
	dev-perl/Test-Exception
	dev-lang/perl"
