# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="ZEFRAM"
DIST_VERSION="0.005"


inherit perl-module

DESCRIPTION="efficient shared mutable hash"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND="dev-perl/Module-Build
	perl-gcpan/Scalar-String
	>=dev-perl/Devel-CallChecker-0.8.0
	dev-lang/perl"
