# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=5

MODULE_AUTHOR="JMEHNLE"
MODULE_VERSION="0.11"

MODULE_SECTION="clamav-client"

inherit perl-module

DESCRIPTION="A client class for the ClamAV C<clamd> virus scanner daemon"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND="dev-perl/Module-Build
	dev-perl/Error
	dev-lang/perl"
