# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="MBRADSHAW"
DIST_VERSION="2.20210112"


inherit perl-module

DESCRIPTION="Send SMTP transaction data to the Abusix transaction feed"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND="dev-perl/Test-Exception
	dev-perl/Moo
	dev-lang/perl"
