# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="TOKUHIROM"
DIST_VERSION="0.08"


inherit perl-module

DESCRIPTION="paranoid dns resolver"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND=">=dev-perl/Net-DNS-1.340.0
	dev-perl/Module-Build
	>=dev-perl/Class-Accessor-Lite-0.80.0
	dev-lang/perl"
