# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="JONASBN"
DIST_VERSION="1.914"

inherit perl-module

DESCRIPTION="Perl extension to OpenSSL's X509 API."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND="dev-perl/Crypt-OpenSSL-Guess
	>=dev-perl/Test-Pod-1.520.0
	>=dev-perl/Convert-ASN1-0.330.0
	dev-lang/perl"
