# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="5"
# SUPPORT_PYTHON_ABIS="1"
PYTHON_COMPAT=( python2_7 )
inherit distutils-r1
# inherit python-r1
DESCRIPTION="Fuglu Mail Content Scanner"
HOMEPAGE="http://www.fuglu.org"
SRC_URI="mirror://pypi/f/fuglu/${P}.tar.gz"
LICENSE="Apache-2.0"
KEYWORDS="~x86"
SLOT="0"
IUSE=""
